### ISSUE TITLE
Mechs spamming messages

### ISSUE THREAD

**Issue by frontline03** [Eclipse-Station/NEV-Northern-Light#1112]
![](https://cdn.discordapp.com/attachments/379912547241033738/785517249687322634/f9e33a781f4e86a1afb239ec197f9dc1.png)

When I get in to a mech, this spams my text box, It also shows up when I join 

![](https://cdn.discordapp.com/attachments/379912547241033738/785518082482634792/4957639b9113f70b2a34f9f5b3774efe.png)

**Comment by Valanthe500** [comment]
I've been unable to replicate this issue myself, but I have found the code that proc'd that message:
![image](https://user-images.githubusercontent.com/23348904/113570668-ae4a4480-95c9-11eb-8225-070152a16d4d.png)
It's under code/modules/mob/living/carbon/human/inventory.dm
Someone who knows a bit more about coding might be able to figure out what's going on, but it seems that something was trying to find an inventory slot that doesn't exist.

**Comment by frontline03** [comment]
I completely forgot this was still up. I believe the issue to have been fixed now, since mechs no longer spam the issue when I get in them, closing the comment
