### ISSUE TITLE
There are no rocks for miners to mine

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/NEV-Northern-Light#120]
When the mining shuttle is taken to an asteroid, instead of having anything to do, there's a bunch of empty turfs and they have to turn around and go back home.

**Comment by bearrrrrrrr** [comment]
I made an issue of this at #119. Planets themselves are generating fine, but without ores. Unsure if that is unintentional or not.

**Comment by EvilJackCarver** [comment]
Closing as duplicate of #119.
