### ISSUE TITLE
Lipstick just shows error: is broken

### ISSUE THREAD

**Issue by CupOfExplodium** [Eclipse-Station/NEV-Northern-Light#1274]
Heya, lipstick just shows a floating "error" on your character.  Either Aranya or Apok said that it's trying to use assets that don't exist.

**Comment by Valanthe500** [comment]
Yep, We're aware of this one, we're currently lacking a sprite for lipstick on models.

**Comment by Valanthe500** [comment]
This issue is resolved by a PR by mci, praise be!

**Comment by MciReloaded** [comment]
Praise be~

**Comment by EvilJackCarver** [comment]
Can I please get a PR number so I can close this one out?
