### ISSUE TITLE
Virus Food Dispenser is not anchored

### ISSUE THREAD

**Issue by Valanthe500** [Eclipse-Station/NEV-Northern-Light#1354]
The VIrus Food Dispenser in Virology appears to be unanchored and pullable, meaning you can drag it off the wall.

**Comment by Valanthe500** [comment]
Seems like a bigger issue, all objects under /obj/structure/reagent_dispensers are set to be unanchored even if they have their var set to TRUE.

**Comment by MciReloaded** [comment]
Fixed in a pushed patch

**Comment by EvilJackCarver** [comment]
Can someone confirm a fix on this so I can close it, and if so, can you please link the PR that fixed it?

**Comment by Valanthe500** [comment]
I can confirm the issue is fixed reagent dispensers are properly anchored no,, but I can't seem to track down the PR that fixed it. will keep looking.

**Comment by EvilJackCarver** [comment]
If you don't find it, don't worry too much about it; I just prefer a decent
paper trail in case a pull causes an issue to recur later down the line.

---
~ R. A. Spitzer

On mobile; typos are my own.
