### ISSUE TITLE
Recycling BSL "Randomizer" tool polish makes your materials disappear from the Bioprinter/Autolathe

### ISSUE THREAD

**Issue by Polyushko1** [Eclipse-Station/NEV-Northern-Light#1388]
Basically what the title says. Attempting to ''Insert Material'' with such a thing in hands actually hides all materials from the bioprinter/autolathe even if it filled. No matter what other material you attempts to insert on it - will stay hidden. You can print things, but can't take any materials off.

**Comment by Valanthe500** [comment]
Still working on a fix for this, but in the mean time, we do have a workaround. If you disassemble the autolathe, it will dump all the items that were inside it on the ground, so you don't lose anything but the randomizer.

**Comment by EvilJackCarver** [comment]
Closed in #1459
