### ISSUE TITLE
Juice Drainage

### ISSUE THREAD

**Issue by Polyushko1** [Eclipse-Station/NEV-Northern-Light#1394]
https://cdn.discordapp.com/attachments/567023102257659914/814391989582954526/unknown.png

For a reason, 6, 4 or 2 units of biomatter is drained from the canister while it is connected with the biomatter tank. If makes something weird when it has 800 biomatter (fulled) and then, goes back to 794/796 and continues to drain.

**Comment by Valanthe500** [comment]
Will need further testing, but what might be happening is the biomatter may be filling the connected fluid pipes which attach the biomatter reactor to the generator and solidifier.

**Comment by Valanthe500** [comment]
With the removal of the fluid pipes (can't find the PR it happened in) this issue no longer seems to be occurring
