### ISSUE TITLE
Throwing out a produce bag causes it to think it is still in your hand

### ISSUE THREAD

**Issue by MciReloaded** [Eclipse-Station/NEV-Northern-Light#1398]
As the title states- throwing away a produce bag causes it to think it is still in your hand. There is no way to remove it from your hand, and it does not exist. However, The only way to fix this is to put it in your bag.

**Comment by faaaay** [comment]
I have this issue, save that putting it in the bag didn't fix it.

**Comment by MciReloaded** [comment]
@TwistedAkai Fixed it. Praise!
