### ISSUE TITLE
Sol Rifle sprite not showing up in hand

### ISSUE THREAD

**Issue by Aleph-NullDDC** [Eclipse-Station/NEV-Northern-Light#1407]
What it says on the tin. Will try and get screenshots soon, but it seems the Sol rifle sprite did not load either on the ground or in hand when I found them in the old maint tunnels

**Comment by Valanthe500** [comment]
Tested, it appears someone tried to make a special version of the Sol to spawn in maintenance, but neglected to give it an actual sprite. Added to the to do list.

**Comment by EvilJackCarver** [comment]
Closed in #1455
