### ISSUE TITLE
Thrown items not damaging benzins

### ISSUE THREAD

**Issue by frontline03** [Eclipse-Station/NEV-Northern-Light#1424]
![image](https://user-images.githubusercontent.com/34557989/111157832-4044cb80-858f-11eb-8cc1-c738e1c2ec6e.png)

**Comment by Valanthe500** [comment]
I have been unable to replicate this issue.
In my testing, a thrown circular saw will attack everything on the tile it lands (hitting/missing as normal) and deal 4 brute damage to  every roach it hits, attackers stats do not appear to have any influence on this.

**Comment by frontline03** [comment]
This seems fixed to me since they do not get damaged by thrown items. closing this.
