### ISSUE TITLE
Skull bandanna does not show when worn on the head

### ISSUE THREAD

**Issue by JaxtalMK2** [Eclipse-Station/NEV-Northern-Light#1432]
Haven't tried with other bandannas yet. but at the least the skull one doesn't display when worn on my head. Fore reference, I do have mouse ears, in case that's interfering, hwoever other hats seem fine?

**Comment by Valanthe500** [comment]
Tested. There are actually two problems, and they affect all bandanas.
Bandanas come in two obj paths:
obj/item/clothing/mask/bandana, and obj/item/clothing/head/bandana

All bandanas under mask can be placed on the head slot, but have no accompanying on mob sprite.
All bandanas under head cannot be equipped as masks.
