### ISSUE TITLE
Typo: Incinerator 

### ISSUE THREAD

**Issue by QuantumPickleJar** [Eclipse-Station/NEV-Northern-Light#1492]

**Comment by EvilJackCarver** [comment]
"Typo: Incinerator" is not nearly enough information for me to be able to tell what's going on. Where is this typo? How is it erroneous?

**Comment by Valanthe500** [comment]
So I had a look into this, and I think I found what they may be reporting, the vent control button in the Incinerator control room is labelled "Incernator Vent."
