### ISSUE TITLE
Benzins have engaged stealth mode

### ISSUE THREAD

**Issue by EvilJackCarver** [Eclipse-Station/NEV-Northern-Light#1500]
Users report benzin roaches have no sprite.

**Comment by EvilJackCarver** [comment]
Closed via direct commit https://github.com/Eclipse-Station/NEV-Northern-Light/commit/21bcb5263e85328b18cd4c236c7f9a45a42001b7

**Comment by drexample** [comment]
https://github.com/Eclipse-Station/NEV-Northern-Light/pull/1501

**Comment by EvilJackCarver** [comment]
my bad, looked like one
