### ISSUE TITLE
Bluespace beakers cannot be made.

### ISSUE THREAD

**Issue by Andron1219** [Eclipse-Station/NEV-Northern-Light#1503]
For some reason they have no 'cost' to make, making them unobtainable in the protolathe.
![bug](https://user-images.githubusercontent.com/78688638/123706306-1f4e7080-d836-11eb-8ac7-de35a1b230c4.PNG)

**Comment by EvilJackCarver** [comment]
Possible cause: https://github.com/Eclipse-Station/NEV-Northern-Light/blob/master/code/modules/reagents/reagent_containers/glass/beaker.dm#L70

MATERIAL_PLASMA is deprecated and doesn't point to phoron as a material.

Similar issue with the Martyr Gift upgrade for the cruciform: https://github.com/Eclipse-Station/NEV-Northern-Light/blob/master/code/modules/core_implant/cruciform/upgrades.dm#L134

**Comment by Valanthe500** [comment]
This appears to have been fixed by #1548 
That merge changed MATERIAL_PHORON to MATERIAL_PLASMA in code/_DEFINES/materials.dm
