### ISSUE TITLE
mooore mapping issues

### ISSUE THREAD

**Issue by benj8560** [Eclipse-Station/NEV-Northern-Light#1554]
Not a massive deal but it's a bit of a endeavor to get a crew member into the sever room to restart the messaging sever. It's only real use now is for sending crew requests with old PDAs being unused. AI ( possibly intentionally?) is unable to see and enable the sever. With how rare a CSO AI being able to see this would be far more ideal.

![dreamseeker_QBxQPelrOg](https://user-images.githubusercontent.com/26511091/137248637-b5330462-4310-4070-82e3-9588be554037.png)

**Comment by Valanthe500** [comment]
Ought to be an easy fix,  just need to move the camera in the Robotics Lab north two tiles.
