### ISSUE TITLE
Gas Mask does not function as a breath mask

### ISSUE THREAD

**Issue by Valanthe500** [Eclipse-Station/NEV-Northern-Light#1570]
I am uncertain if this is intended behaviour, and I will need to assess it further to find out if all gas masks are affected this way, or just the one, but currently the default Gas Mask (/obj/item/clothing/mask/gas) does not function as a breath mask.

**Comment by MciReloaded** [comment]
Looking at the code for gas mask, it states it should be able to be connected to an air supply

**Comment by MciReloaded** [comment]
After running a test, I can **confirm** that gas masks **are** working as a breath mask.

**Comment by Valanthe500** [comment]
I've also done further testing on my end and have been unable to reproduce this issue, even matching the events of the first report as closely as I can.

I think we can close this as a one-time issue, or more likely, some kind of user error that I didn't catch in my initial investigation.
