### ISSUE TITLE
Blob can spawn on the Centcom map

### ISSUE THREAD

**Issue by Valanthe500** [Eclipse-Station/NEV-Northern-Light#1580]
![image](https://user-images.githubusercontent.com/23348904/141111403-1c249b94-3390-440e-96b2-5959c5b38bc0.png)
As it says on the tin, the Blob can apparently spawn on the "Centcom" Z-Level. This one in particular spawned inside the supply shuttle's holding area.

![image](https://user-images.githubusercontent.com/23348904/141111813-fcb42bc3-c869-4253-bc83-ef56bc801aa6.png)

**Comment by MciReloaded** [comment]
So if we fix this, consider. Make it an event where a blob or other dangerous things get sent through the shuttle.

**Comment by EvilJackCarver** [comment]
Wgat.

**Comment by Valanthe500** [comment]
You know it's a good day when you get the "Oh god oh fuck" tag.

**Comment by EvilJackCarver** [comment]
> 
> 
> You know it's a good day when you get the "Oh god oh fuck" tag.

![](https://user-images.githubusercontent.com/1784490/141134156-1602fdbe-0e93-4f76-a2dd-29b57410bb0d.jpg)

**Comment by Valanthe500** [comment]
I've been trying to replicate this issue since I first posted it. After spawning more than 2,000 Blobs, they have never again spawned off the ship. 
I've also double and triple checked that none of the centcomm areas have "ship_area = true" as that var is required for it to appear as a valid place for the blob to spawn. 
I've run out of possible explanations why this happened.

**Comment by EvilJackCarver** [comment]
I'm going to chalk it up as a one-off issue, then, and close it.
