### ISSUE TITLE
[Security] Workflow compile_changelogs.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Ale0x78ButInBinary** [Eclipse-Station/NEV-Northern-Light#1602]
The workflow compile_changelogs.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by drexample** [comment]
What the- 
This sounds like a scammer

**Comment by EvilJackCarver** [comment]
All compile_changelogs.yml does is configure the compiler for changelogs posted in the pull requests. Worst case scenario, we lose changelogs for a bit while Nestor works out the kinks behind it. 

Given that changelogs aren't *strictly* required for the server to run, we can do without them if necessary.

Closing as won't-fix.
