### ISSUE TITLE
The Button to Vent the Supermatter Core is not working

### ISSUE THREAD

**Issue by Sly9sky** [Eclipse-Station/NEV-Northern-Light#1604]
The Vent Engine button- above maintenance drone in this picture- does not open the reactor blast door to space which would allow rapid venting. Moreover, when Carver attempted to run 'View Variables', it caused him to disconnect.
![image](https://user-images.githubusercontent.com/87826427/147997008-53c1b612-eb1d-48d9-9e88-19d63bf9df57.png)

**Comment by Valanthe500** [comment]
With the new map I can confirm that the vent core button (located behind the glass next to the eject button) does indeed open  two blast doors to vent the core, as pictured:
![image](https://user-images.githubusercontent.com/23348904/164965810-a0968fdc-d614-4733-b14e-5c450e59e68a.png)
closed (normal operation)
![image](https://user-images.githubusercontent.com/23348904/164965831-f51f1087-fcf5-4249-9e34-611cd3752ea1.png)
open

**Comment by Sly9sky** [comment]
Closed it given that the fixes were implemented.
