### ISSUE TITLE
Maintenance areas on the new map are not shielded from radiation.

### ISSUE THREAD

**Issue by Solazius** [Eclipse-Station/NEV-Northern-Light#1623]
Exactly what it says on the tin!
 A radiation storm is more or less a guaranteed death sentence everywhere on the vessel, save for the primary cryopod room.
 
~~At least we're safe in the tubes~~

**Comment by GuiltyNeko** [comment]
Having stood in maintenance during a rad storm, I'm pretty sure maints is fine, it just doesn't LOOK like it's fine.

**Comment by Solazius** [comment]
That's... Incredibly strange. The cryo storage rooms don't get the radiation overlays like the rest of the ship does.
I was playing as a full synth at the time, so I can't really confirm or deny whether they actually do mutate the hell out of you or not.
I would simply check the map and see, though I'm not entirely sure how myself.

**Comment by GuiltyNeko** [comment]
I may have found the issue, though it's a purely visual one.
 [code](https://github.com/Eclipse-Station/NEV-Northern-Light/tree/master/code)/[game](https://github.com/Eclipse-Station/NEV-Northern-Light/tree/master/code/game)/[gamemodes](https://github.com/Eclipse-Station/NEV-Northern-Light/tree/master/code/game/gamemodes)/[events](https://github.com/Eclipse-Station/NEV-Northern-Light/tree/master/code/game/gamemodes/events)/[weather](https://github.com/Eclipse-Station/NEV-Northern-Light/tree/master/code/game/gamemodes/events/weather)/rad_storm.dm
This decides what areas are protected from the purely VISUAL, weather effects of the rad storm. I'll be updating this in about 3 minutes or so.

**Comment by Solazius** [comment]
#1624 seems to have fixed this one. Woo! Great job, team.
