### ISSUE TITLE
R&D Shuttle only transports part of itself to the destination

### ISSUE THREAD

**Issue by Valanthe500** [Eclipse-Station/NEV-Northern-Light#1644]
To replicate: Send the R&D shuttle to a destination.

The back 2/3 of the ship will leave, leaving the cockpit, the two small rooms, and an empty copy of the ship behind, while the back of the ship goes to get stuck in limbo, never reaching a destination, and permanently breaking the shuttle for that round:
![image](https://user-images.githubusercontent.com/23348904/162858087-aff94b64-a5ca-4349-a482-d6742ac39e6a.png)
![image](https://user-images.githubusercontent.com/23348904/162858406-7bca9795-cd59-42f0-a0b0-1bea88cbb663.png)

At first I suspected a mapping issue, but it appears to be a cohesive area, so I can't figure out what's broken it.

**Comment by GuiltyNeko** [comment]
Of note, the shuttle is set up identically to how it is on the eris map, so this really shouldn't be happening.

**Comment by Valanthe500** [comment]
So one thing I've noticed, when I sent the shuttle off in those pics, the back portion does not appear to have actually gone to the proper "transition" zone on the Centcomm map.

**Comment by Valanthe500** [comment]
Issue has no been resolved through no action of anyone involved so far as I can tell. Tested every  single destination tonight, sometimes returning to the Northern Light, other times hopping between the points directly, and did not encounter a single issue.
