### ISSUE TITLE
"Fitness Room" area extends into space

### ISSUE THREAD

**Issue by Valanthe500** [Eclipse-Station/NEV-Northern-Light#1716]
The area surrounding the Holodeck on the Erida map is labelled "Fitness Room," and this area extends into space on several tiles.

Relatively minor issue, but it was discovered when a Deep-Maint entrance spawned on these space tiles, causing the player to surface in space.

**Comment by EvilJackCarver** [comment]
Won't-fix - that area define is necessary for the EVA lighting to function. While it's not exactly *intended* behaviour that deepmaint can exit in an area outside the ship, it still makes sense within the lore of deepmaint for it to potentially exit there (and deepmaint is dangerous as hell, yo).
