### ISSUE TITLE
Cleaning Items

### ISSUE THREAD

**Issue by The-Good-Doktor** [Eclipse-Station/NEV-Northern-Light#1724]
I love the idea of the floor becoming dirty over time, but when theres no custodians it will get very dirty, very fast. Thinking maybe to remedy this, add cleaning stations that the general public can get to?

**Comment by Valanthe500** [comment]
That is something we used to have on the old map, and a good idea. I'll see about adding some mops/buckets scattered around the ship for use.

**Comment by The-Good-Doktor** [comment]
Maybe a "Tersus" vacuum cleaner for the club? would make it quicker and easier for the club workers and less wet floors for the patrons of the bar

**Comment by Valanthe500** [comment]
Eh, I don't want to make it too easy to clean up without the church, to encourage people to call them when they're around. I'll add  some extra utility items to the closet though in exchange, like a trash bag and light replacer.

**Comment by The-Good-Doktor** [comment]
Sounds perfect to me!
