### ISSUE TITLE
Body colouration code is fucky for Unathi and Highlander Zorren sprites

### ISSUE THREAD

**Issue by EvilJackCarver** [Eclipse-Station/NEV-Northern-Light#19]
When full white is selected, the body is roughly 50% grey.

![image](https://user-images.githubusercontent.com/1784490/81029496-c90cba00-8e4a-11ea-874c-e92e876ecf39.png)

This is also slightly less of an issue with highlander Zorren.

![image](https://user-images.githubusercontent.com/1784490/81029660-78499100-8e4b-11ea-8fc0-7ca3585d4cdb.png)

**Comment by Jakksergal** [comment]
I am not a coderman so I don't know what to make of the actual code but in Virgo they use a boolean var called color_mult which resolves this. Seems like every species and set of living/carbon/ sprites (hair, tails, etc) has this var.

**Comment by EvilJackCarver** [comment]
Since - to the extent of what I've been told and know - the body colour was fixed by #22 and Zorren colouration is a lore thing, I'm closing it now.
