### ISSUE TITLE
tails are layered wrong

### ISSUE THREAD

**Issue by Greenjoe12345** [Eclipse-Station/NEV-Northern-Light#21]
![image](https://user-images.githubusercontent.com/33647525/81030076-5ec23c80-8e7f-11ea-9f64-f6c9125d53df.png)
the tail is behind the sprite when it should be in front for facing north

**Comment by EvilJackCarver** [comment]
Duplicated by #24 and #26. 

I'm closing this and 24 in favour of 26, as 26's scope seems to be more accurate.
