### ISSUE TITLE
Consuming pills/crafting items in-hand will result in sprite still showing.

### ISSUE THREAD

**Issue by bearrrrrrrr** [Eclipse-Station/NEV-Northern-Light#23]
![image](https://user-images.githubusercontent.com/54826962/81037263-164f5280-8e70-11ea-900c-be32b431b183.png)

A la the above- I've dropped the igniter AND weapon assembley, but they still show. At that moment I was only holding the flamethrower.

Unsure what it's caused by. A consistent way to recreate it is by trying to craft something when you have the item in-hand or by taking a pill.

**Comment by Chatter42** [comment]
It might be helpful to know this also happens with aggressive grab intent or when folding an empty box.

**Comment by bearrrrrrrr** [comment]
Addition: also happens when deploying roller beds.

**Comment by EvilJackCarver** [comment]
@drexample, did Eris already have code for separate arms/hands, or did you port that from ES13/EW code? If it's the latter, it's entirely possible that the grab/hand system is working off the player's *arms* instead of hands.
