### ISSUE TITLE
Biogenerator doesn't function

### ISSUE THREAD

**Issue by Ikmachek** [Eclipse-Station/NEV-Northern-Light#247]
With biomatter in a tank and the required valves open, when you press 'activate bio generator' on the console it returns 

"The biogenerator screen states, 'Biogenerator now inactive.'" not generating any power at all.

**Comment by Andromeda-K22** [comment]
fix will be up soon

**Comment by ShadzFen** [comment]
Bump reminder that this issue got fixed in the latest update. This ticket should be closed
