### ISSUE TITLE
Insulated gloves are only technically doing what they're supposed to do

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/NEV-Northern-Light#25]
When wearing insulated gloves and interacting with something that has been electrified, your hands will be completely safe, as intended. Your **arm**, however, will get zapped anyway, because gloves don't care about your arms.
![image](https://user-images.githubusercontent.com/32618785/81102188-e1c1b200-8ed4-11ea-9685-8fae0d706a86.png)

**Comment by EvilJackCarver** [comment]
May be related to #23.
