### ISSUE TITLE
Sprites-that-don't-display-in-hand dump

### ISSUE THREAD

**Issue by ShadzFen** [Eclipse-Station/NEV-Northern-Light#271]
This is an issue post where all sprites that don't show up at all when held in hand can be posted in order to be fixed. Please feel free to post a comment with the names of any objects that haven't been mentioned before! There are a lot of sprites, and any help finding as many as possibly is greatly appreciated~

Formatting is `icon_state` name followed by `(ingame name)` in parenthesis. If you don't know the icon_state name, ingame name should be enough.

DO keep in mind that an item's held sprite can sometimes be **very small**. Make sure it really is invisible.
You can be extra sure by going to the upper left corner of your SS13 window and setting the scale to max. Set it back to stretch once you're done to get your screen back to normal!
![image](https://user-images.githubusercontent.com/45645502/86419914-09ff3e80-bcd5-11ea-973d-4acdcbc48286.png)   ![image](https://user-images.githubusercontent.com/45645502/86419808-b8ef4a80-bcd4-11ea-9e66-b9d58adf54b7.png)

icon_state 		-			(ingame name)
--------------------------------------------------------------------------------
crowbar - (crowbar)
walkietalkie 		-			(radio)
taperoll 			-		        (duct tape)
pda - (PDA)
pliers - (pliers)
engineering_tool 		-		(engineering tools pouch)
deliveryPaper 			-		(package wrapper)
deliverycrate2 			-		(small parcel)
sheet_plastic, sheet_plastic_2, sheet-plastic_3  -  (plastic sheets)
breath 				-		(breath mask)
miner_suit 			-		(mining voidsuit)
plate 				-		(reinforced plating)
igniter                               -               (igniter)
prox 				-		(proximity sensor)
hammer_addon 		-		(flat surface)
heatsink                            -               (heatsink)
cpuboard 			-		(standard processor board)
infrared				-	        (infrared emitter)
o2, firstaid-o2			-		(oxygen deprivation first aid)
utility				-		(tool belt)
[pretty much every single design disk]
welderpack			-		(welding kit)
matter_bin			-		(matter bin)
bshell				-		(beanbag shell)
lighter-y				-	        (cheap lighter)
matchbox                          -              (matchbox)
match_unlit			-		(match)
glass_empty			-		(glass)
freezer				-		(portable freezer)
tastybread			-		(bread tube)
space_twinkie			-		(space twinkie)
cheesie_honkers		-	        (cheesie honkers)
4no_raisins			-		(4no Raisins)
sosjerky				-	        (Scaredy's Private Reserve Beef Jerky)
ramen				-		(Cup ramen)
utility_neotheology		-		(mekhanite utility belt)
?? - Engineering hardhat
?? - Reinforced medical shoes

FS CAR .20 "Z8 Bulldog" has no two-handed sprite

**Comment by ArbyTheDragon** [comment]
The FS CAR .20 "Z8 Bulldog" has no sprite when wielded, but is fine when not wielded.
![image](https://user-images.githubusercontent.com/15035655/87268331-b5578280-c48f-11ea-9d59-0fa031b6157f.png)

**Comment by EthanSedgwick** [comment]
Engineering hardhat + Reinforced Medical Shoes should be included.
