### ISSUE TITLE
mind flayer man no work

### ISSUE THREAD

**Issue by bearrrrrrrr** [Eclipse-Station/NEV-Northern-Light#282]
what happen:

When press activate on mind frayer man, it supposed to make people go 'WOWIE!!!!! BREAKDOWN TIME AAAAAAA'

but it not do that

How 2 replicate:

activate mindfrier

thank yuo

**Comment by EvilJackCarver** [comment]
![23c15a4a-622a-4c91-94ec-eae567060284](https://user-images.githubusercontent.com/1784490/86979045-e8bfa780-c145-11ea-81e5-1797dfe816ec.png)

I have no clue what you're trying to say, whether this is a genuine issue ticket, or whether to close it for shitposting.

**Comment by ShadzFen** [comment]
Bump to close this ticket since it's been confirmed this is not an issue.

**Comment by bearrrrrrrr** [comment]
Yeah, it's not an issue. This was actually due to me not understanding how the mindflayer worked.

There is a bug associated with it and the traitor contracts, but that is seperate and I will post it later.
