### ISSUE TITLE
Transforming into a monki as a 'ling both keeps your name and ears/tail

### ISSUE THREAD

**Issue by bearrrrrrrr** [Eclipse-Station/NEV-Northern-Light#288]
http://puu.sh/G3YOx/d024e54858.jpg
http://puu.sh/G3YP7/002a2e1e11.jpg
http://puu.sh/G3YOP/30c920ff59.jpg

help

ADDITIONALLY:

turning back into a person from monki turns you to RGB 0, 0, 0

http://puu.sh/G3YQY/69d64c090a.jpg

**HOW TO REPLICATE:**

become monki power changeling

**Comment by Valanthe500** [comment]
I believe this issue is no longer relevant as changeling has been removed on our code, and replaced with carrion, who does not have a direct "change into monkey" power.
