### ISSUE TITLE
Mining equipment lockers refuse to unlock without using ID in-hand

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#296]
Not sure if this issue extends to other lockers. To replicate, click or alt-click on a locked locker with an ID, or with ID in PDA on ID slot. Locker will respond with "Access denied", but once the ID is used directly in-hand on the locker, it will say it's unlocked without actually unlocking. Past this point, left and alt-click work as normal with the ID worn.

**Comment by EvilJackCarver** [comment]
Functions as intended: Mining lockers (as well as other departmental lockers) function as personal lockers, and miners' IDs don't have the proper access to unlock personal lockers' without the owner's consent. Swiping the ID across the locker (if there's no owner set) will set the owner to the name on the ID.

**Comment by Ashturian** [comment]
Would it be best to give the players a prompt to use the ID directly on the locker if it doesn't have an owner set yet, and some indication when one is owned if claiming a locker prevents other equal ID's from unlocking them?
