### ISSUE TITLE
Using the "Gulp Down" verb turns orange juice cartons invisible

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#299]
Haven't tested with other similar carton-type containers, yet, but replicated twice with orange juice cartons.

**Comment by Valanthe500** [comment]
Confirmed issue is still present, affects all carton based drinks.

**Comment by MciReloaded** [comment]
Issue exists for: Orange Juice, Lime Juice, Tomato Juice, it seems to be anything that comes in a "bottle" format, as the things described as being in "Cartons" are subsections of the bottle type. It calls itemname_empty to make an empty version of what was consumed, even though anything in a carton does not HAVE a sprite for being "empty"
