### ISSUE TITLE
Colour selector "New" swatch doesn't update except when clicking on the palettes

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#300]
Changing the RGB values or pasting a colour hex value doesn't update the new colour, only clicking in the colour palettes themselves does.

**Comment by Valanthe500** [comment]
I cannot say for certain when this was fixed, but I've tested this on the live server and all colour options (palette, RGB values, and hexcode) are all working in the character setup window. Unless you are referring to a colour selector from somewhere else, I believe this is resolved.
