### ISSUE TITLE
Downward vertical pipes missing at 112, 96, 3 and 112, 97, 3

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#301]
There is a matching set of upward vertical pipes on the floor below, as pictured.

![NEV Northern Light 2020-07-07 205553](https://user-images.githubusercontent.com/53239656/86876376-2257ca80-c0d4-11ea-8aba-49653817d406.png)

**Comment by EvilJackCarver** [comment]
Closed in #1459
