### ISSUE TITLE
Roles with spawn items don't spawn with them in Dormitory spawnpoint.

### ISSUE THREAD

**Issue by ShadzFen** [Eclipse-Station/NEV-Northern-Light#314]
Any role that spawns with an item, for example CMO who starts with an advanced medkit, will not have that spawn item at all if they spawn in the Dormitory spawn. It's not even under the bed or anything. If you spawn in the cryopods however, the item will be in the pod when you eject out of it.

![image](https://user-images.githubusercontent.com/45645502/86956152-f16da900-c158-11ea-97c8-4e69dc48ea3e.png) ![image](https://user-images.githubusercontent.com/45645502/86956172-faf71100-c158-11ea-8088-12bbfd819030.png)
![image](https://user-images.githubusercontent.com/45645502/86956160-f599c680-c158-11ea-965f-2225135da086.png) ![image](https://user-images.githubusercontent.com/45645502/86956185-fd596b00-c158-11ea-9a57-1077eebe5bec.png)

**Comment by EvilJackCarver** [comment]
Flagging high-pri
