### ISSUE TITLE
Paramedics cannot open paramedic lockers

### ISSUE THREAD

**Issue by cruxxansata** [Eclipse-Station/NEV-Northern-Light#34]
What it says on the tin. Paramedics cannot unlock the "paramedic lockers" in the paramedic's closet. They just don't seem to have the access necessary.

**Comment by bearrrrrrrr** [comment]
Have you tried pulling your card out of your PDA and swiping it over the locker?

**Comment by EvilJackCarver** [comment]
Confirmed nonissue in dev environment by ShadzFen: Most, if not all, equipment lockers act like personal lockers - you need to swipe your ID on them directly to claim, after that you'll be able to alt-click unlock.
