### ISSUE TITLE
Community doesn't like new radio noise

### ISSUE THREAD

**Issue by bearrrrrrrr** [Eclipse-Station/NEV-Northern-Light#340]
additional context:

http://puu.sh/G693Q/d4ed0d8e73.png

**Comment by EvilJackCarver** [comment]
Bear, I would **strongly appreciate** it if you would maintain some degree of professionalism here. While the message is received loud and clear that the community as a whole doesn't like the new radio noise (and I'll work on a revert in the coming days), I would like to state here that I take this somewhat seriously and I would appreciate it if you would as well.

**Comment by bearrrrrrrr** [comment]
aye, apologies

**Comment by bearrrrrrrr** [comment]
To be honest it's also grown on me a lot.

Might be worth looking into what other people think rather than a complaint/bug report that was made in 30 seconds as partially a joke

**Comment by Ikmachek** [comment]
It's not grown on me, to be honest it just sounds more sloppy/gory/sqlechy than radio.

**Comment by ArbyTheDragon** [comment]
It sounds just fine to me. I love sounds, cause sometimes the ambience either doesn't play or just stops.

**Comment by EvilJackCarver** [comment]
I'll take a look at how the community feels about it Friday via discord and
take whatever action the community votes for then.

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by MciReloaded** [comment]
Is this still a thing being considered, or can it be closed?

**Comment by EvilJackCarver** [comment]
This was in relation to when I added a couple of extra squelch sounds, it can probably be closed.
