### ISSUE TITLE
Oddity perks don't work

### ISSUE THREAD

**Issue by Ikmachek** [Eclipse-Station/NEV-Northern-Light#347]
If you level up with an oddity in your hand/inventory that has a perk tied to it, you don't get the perk. Confirmed by looking at the 'show stats' IC verb.

**Comment by EvilJackCarver** [comment]
Is it a certain perk or all perks?

**Comment by Acryonic** [comment]
I tested with the oddity held in the other hand, did not seem to add the oddity perk itself.
Heres a screencap of both the confirmation of rested, bonus to stats applied and the oddity perk in question.
![Oddityperks1](https://user-images.githubusercontent.com/64962881/87761655-21304700-c812-11ea-86cf-2535da880d3d.PNG)
