### ISSUE TITLE
 FS CAR .20 "Z8 Bulldog" has no two-handed sprite

### ISSUE THREAD

**Issue by ShadzFen** [Eclipse-Station/NEV-Northern-Light#349]
Yet another invisible gun when held with both hands. Probably the exact same issue as the sawnoff shotgun had.

![image](https://user-images.githubusercontent.com/45645502/87326645-49c6f100-c533-11ea-97e9-91d9585a9e62.png)

**Comment by EvilJackCarver** [comment]
Closing as duplicate - already mentioned in megathread.
