### ISSUE TITLE
Knockback and Simple Mobs

### ISSUE THREAD

**Issue by Leon9621** [Eclipse-Station/NEV-Northern-Light#354]
Assuming spiders are simple mobs, anyway. 

Acquire shotgun and buckshot.
Take aim at a nearby spider, within 3 tiles.
Use shotgun to make spider horizontal.
Marvel as the spider bounces off of the walls and, in fact, flies TOWARD you, simply defying the laws of physics and common sense.
Note that it smashed into every window along the way in approximately one attosecond.

https://i.imgur.com/Rbjeijn.png

**Comment by Leon9621** [comment]
Small correction, it only smashed into ONE window.

**Comment by Leon9621** [comment]
Happened again. 

https://i.imgur.com/hDG50W9.png

Started at the bottommost slug there, near the window to space. The spider somehow drifted up, AROUND the corner, and flew another 4 spaces before finally landing. I did also see the cloud of shot following the spider's mob, but good god is this hilarious.

**Comment by EvilJackCarver** [comment]
I say we leave the bug in if it's causing spiders to drift around corners
like a Toyota owned by a tofu delivery company

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by EvilJackCarver** [comment]
Looking back at it, it has the potential to negatively affect gameplay, so I'm flagging it as a bug. If someone can get a video or GIF of it happening that'd be great.

**Comment by Valanthe500** [comment]
This has potentially been fixed now as of Upstream Merge #1595 

Knockback from shotguns has been restricted to 5 tiles.
