### ISSUE TITLE
Newscaster updates are all wanted notices

### ISSUE THREAD

**Issue by Ikmachek** [Eclipse-Station/NEV-Northern-Light#36]
When there's any kind of announcement like space dust or ion storms, the newscasters say there's a wanted notice posted ontop of that.

How to reproduce: Wait or force an event standing by a newscaster

**Comment by Valanthe500** [comment]
This has definitely been fixed at some point, but I honestly can't find the code that handles these newscaster announcements, so I am not certain when, but I've tested several different types of announcement / event:
![image](https://user-images.githubusercontent.com/23348904/143674012-4d4a7dca-b232-4c37-9540-943e67d64c71.png)
