### ISSUE TITLE
Antag uplink unit missing a sprite

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#363]

**Comment by EvilJackCarver** [comment]
In-world or inventory sprite?

**Comment by Ashturian** [comment]
It was the in-world, and inventory sprites, the uplink unit functioned as normal, but I haven't been able to test under the same conditions as in-game.

The exact conditions were:
My character was made into a crew-sided antag/Marshal, while naked, shortly after being cloned.
