### ISSUE TITLE
Single-name characters create portmanteaus when joining as jobs that override the first name

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/NEV-Northern-Light#368]
If you join certain jobs, such as Aegis Operative, Gunnery Sergeant, or Captain, your character's first name will be overridden. This is not a problem in and of itself, but if you join as a character that only has a first name, then the game seems  to get a little confused and combine the job title with the character's name.
![image](https://user-images.githubusercontent.com/32618785/87439113-006bb580-c5b6-11ea-9f90-91661e83c073.png)
![image](https://user-images.githubusercontent.com/32618785/87439164-111c2b80-c5b6-11ea-8e3c-4675760ea549.png)
![image](https://user-images.githubusercontent.com/32618785/87439181-17120c80-c5b6-11ea-826f-caa27ddc6058.png)

**Comment by EvilJackCarver** [comment]
Closed by #402
