### ISSUE TITLE
Floating chat messages stop disappearing on escape pods

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#380]
Seems to happen only around evac and the dock afterwards, and queues up more than the usual five or so messages that runechat is meant to display at once per person. Could not replicate locally with any of the same conditions at evac.
![NEV Northern Light 2020-07-09 161415](https://user-images.githubusercontent.com/53239656/87782621-6a889280-c822-11ea-80ad-6c6e215216ad.png)

**Comment by EvilJackCarver** [comment]
Need to see if it's able to be consistently reproduced before I assign it the triage tags
