### ISSUE TITLE
Closed lockers aren't considered push-points for zero-G

### ISSUE THREAD

**Issue by ShadzFen** [Eclipse-Station/NEV-Northern-Light#409]
You can't use closed lockers to push yourself around a zero G environment, unlike tables and walls. Pretty sure this isn't supposed to happen.

**Comment by Acryonic** [comment]
Couldn't this be a byproduct of the fact you can drag a locker around usually? compared to a table which can't be moved around without disassembly?

**Comment by ShadzFen** [comment]
It's not like that on a single other codebase that I've seen. Closed lockers have always been zeroG push points. Whether that's something new in Eris or not, I dunno
