### ISSUE TITLE
Crime scene kits hold too much

### ISSUE THREAD

**Issue by Luxspectra** [Eclipse-Station/NEV-Northern-Light#438]
Crime scene kits seem to be bluespace-enabled. This is likely unintentional.
![image](https://user-images.githubusercontent.com/14794167/89092219-d1a75a80-d37d-11ea-9799-658ce91e52dc.png)
![image](https://user-images.githubusercontent.com/14794167/89092230-e126a380-d37d-11ea-8c47-c5a1d2abe516.png)

**Comment by Chatter42** [comment]
![image](https://user-images.githubusercontent.com/32618785/89092348-935a6d00-d376-11ea-904e-574307128ae6.png)

**Comment by Chatter42** [comment]
![image](https://user-images.githubusercontent.com/32618785/89092462-97d35580-d377-11ea-993f-5dc966de87d2.png)
![image](https://user-images.githubusercontent.com/32618785/89092595-bc7bfd00-d378-11ea-84d6-b2ca0eb79f46.png)

**Comment by bearrrrrrrr** [comment]
solution: resprite into cargo pants 
![image](https://user-images.githubusercontent.com/54826962/89094965-58b4fc80-d397-11ea-9277-1d217fab72a3.png)

**Comment by Valanthe500** [comment]
Confirmed Crime scene kits are still TARDIS's.

**Comment by EvilJackCarver** [comment]
Closed in #1459
