### ISSUE TITLE
NEV Northern Light has stolen the helm computer from the CEV Eris!!!!

### ISSUE THREAD

**Issue by Warbidon** [Eclipse-Station/NEV-Northern-Light#442]
Helm Control computer has a header on it sUI labeled "CEV Eris", specifically the one located on bridge.

**Comment by Warbidon** [comment]
#12

**Comment by Valanthe500** [comment]
Issue has been resolved.

**Comment by EvilJackCarver** [comment]
Can you please link the PR so I can close this proper?

**Comment by Valanthe500** [comment]
Can't find the exact PR, history doesn't show any changes, but I've just confirmed on the live server that the ui reads "NEV Northern Light Helm Control" now.

**Comment by EvilJackCarver** [comment]
Closing per above.
