### ISSUE TITLE
Top right UI buttons function incorrectly

### ISSUE THREAD

**Issue by Warbidon** [Eclipse-Station/NEV-Northern-Light#443]
In the topright corner of the UI are a half dozen buttons with, mainly the ones labeled "WIKI", "GITHUB" "RULES" "CHANGELOG" in no particular order.

"WIKI", when clicked produces the following error.
The wiki URL is not set in the server configuration.

GITHUB activates, but points to the CEV ERIS codebase by Discordia, probably incorrect.

"RULES" does not actually do anything, as does changelog.

EDIT: Changelog actually opens it just takes a while.

**Comment by EvilJackCarver** [comment]
Closing: this is a configuration issue, not a code issue. I'll forward it to Nestor.
