### ISSUE TITLE
Excelsior Drozd .40 listed as taking .35 ammo in Excelsior Autolathe entry

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#458]
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/2dcad14695a552bed0d5d692773256fed251b337/code/datums/autolathe/guns.dm

https://github.com/Eclipse-Station/NEV-Northern-Light/blob/bd06536ce637d39cec93d4b827ae0e346c8189aa/code/modules/projectiles/guns/projectile/automatic/drozd.dm

**Comment by EvilJackCarver** [comment]
Closed in #1445
