### ISSUE TITLE
Removing cable restraints rounds the time remaining down to zero minutes

### ISSUE THREAD

**Issue by Ashturian** [Eclipse-Station/NEV-Northern-Light#462]
You attempt to remove the cable restraints. (This will take around 0 minutes and you need to stand still)

**Comment by Valanthe500** [comment]
Confirmed this has been fixed:
![image](https://user-images.githubusercontent.com/23348904/142753710-0c73144d-ab11-44dd-b40f-8c9064fa921d.png)


Appears to have been fixed as of #1479
