### ISSUE TITLE
Some objects have invisible held icons, despite working worn icons

### ISSUE THREAD

**Issue by EthanSedgwick** [Eclipse-Station/NEV-Northern-Light#571]
Reinforced Medical Shoes are invisible when held, but when worn they can be seen. The icon needs to be added for the held/dropped item.

**Comment by EthanSedgwick** [comment]
Engineering hardhat is invisible when held, but when worn works fine.

**Comment by EvilJackCarver** [comment]
Please post this in the megathread

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by EvilJackCarver** [comment]
Closing as duplicate of #271
