### ISSUE TITLE
Multiple Alien Seed Growth error messages appear at the start of every new round

### ISSUE THREAD

**Issue by EthanSedgwick** [Eclipse-Station/NEV-Northern-Light#574]
Happens everytime at round start.

**Comment by Valanthe500** [comment]
Rest in peace Alien Seed Growth, you may be gone but never forgotten. However now instead of one message, we get treated to this:

![image](https://user-images.githubusercontent.com/23348904/142752904-607cf549-20e8-49f6-9df8-35f43b7f51ac.png)
