### ISSUE TITLE
Many roles don't spawn in their offices at Round Start.

### ISSUE THREAD

**Issue by EthanSedgwick** [Eclipse-Station/NEV-Northern-Light#575]
Pyschiatrist, Chief Engineer (spawns in Bridge office instead of Engineering office), etc.

**Comment by Valanthe500** [comment]
Psychiatrist definitely needs to be fixed, as they're currently set to spawn outside of the isolation rooms for some reason.

All heads of staff spawn in the Heads of Staff meeting room at round start, this is intended.

Once the new map update is pushed I will review the spawn points again and revisit this issue.

**Comment by EvilJackCarver** [comment]
Due to the upcoming map changes, I'm going to flag this as "Won't Fix". Nestor has someone working on a different map (specially for our code!) and once that's done and added in, this will most likely be no factor.
