### ISSUE TITLE
One of the cryo storage areas that you spawn in at round start, starts with 10-20 roaches

### ISSUE THREAD

**Issue by EthanSedgwick** [Eclipse-Station/NEV-Northern-Light#576]
Many areas of the setation start with roaches and spawning there by readying up will guarentee your death. This is a critical bug.

**Comment by EthanSedgwick** [comment]
The general sentiment of people seems to be to just remove that as a spawn location.

**Comment by Valanthe500** [comment]
If this is referring to Starboard Cryo, this is working as intended. This is a maintenance cryo, and thus it's in maintenance, and yes, roaches can and do spawn there.

**Comment by EvilJackCarver** [comment]
I'm going to leave this open for now, in case they're not referring to starboard cryo.

**Comment by EvilJackCarver** [comment]
I haven't heard that they're not referring to the starboard cryo; and this issue is technically deprecated with the introduction of the Erida map, so closing as functions as intended/wontfix.
