### ISSUE TITLE
Suit sensors seem to be in a buggy/inconsistent state

### ISSUE THREAD

**Issue by EthanSedgwick** [Eclipse-Station/NEV-Northern-Light#584]
We can't seem to ( (or atleast find the variable to) activate or deactive suit sensors. Some crew spawn with suit sensors on (Union Miner), others don't (Cargo Tech).

**Comment by drexample** [comment]
You need a screwdriver to set suit sensors. This is not a bug, but will probably get changed as QoL in the future.
