### ISSUE TITLE
Isturf check makes solar panels impossible to build without glitching your character.

### ISSUE THREAD

**Issue by TwistedAkai** [Eclipse-Station/NEV-Northern-Light#662]
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/08b8472a083d0967d11ec4baf72c9f18f4590b42/code/modules/power/solar.dm#L247

This !isturf check should not exist. It was added by a lazy refactor 3 years ago. There's supposed to be an isturf check to prevent wrenching the assembly in an inventory (on quality_bolt_turning). Instead, this prevents adding glass unless it's anchored in an inventory, which creates the solar panel, but locks the assembly permanently in that inventory.

I propose changing this line to only check for anchored, and adjusting Quality_bolt_turning above it to either require isturf(loc) to be true for a simple fix or have it force the assembly to drop to turf if it's not for a more complicated but possibly more user friendly fix.

**Comment by Valanthe500** [comment]
Fixed as of #850.
