### ISSUE TITLE
Probable typo. Cheese_food listed twice in tastes for sanity

### ISSUE THREAD

**Issue by TwistedAkai** [Eclipse-Station/NEV-Northern-Light#664]
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/834f81973902be9559deef5d5988f1bf252de292/code/modules/reagents/reagent_containers/food/snacks.dm#L2775

Not sure what should be here instead of a second cheese_food.

**Comment by Valanthe500** [comment]
This has been fixed as of #832 
Mushroompizza is now listed as "CHEESE_FOOD, UMAMI_FOOD"

However the individual slices are listed as "VEGAN_FOOD, VEGAN_FOOD, UMAMI_FOOD"

If I'm reading this right, That means that a Mushroom Pizza doesn't count as Vegan until its sliced, at which point it's DOUBLE vegan....
