### ISSUE TITLE
Language key conflict makes language hard to use.

### ISSUE THREAD

**Issue by TwistedAkai** [Eclipse-Station/NEV-Northern-Light#696]
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/006549e2350825506888bbdda8a72a2946f2396f/code/modules/mob/language/german.dm#L6
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/006549e2350825506888bbdda8a72a2946f2396f/code/modules/mob/language/synthetic.dm#L61
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/006549e2350825506888bbdda8a72a2946f2396f/code/modules/mob/language/synthetic.dm#L72

Three separate languages all share d as the key, making german and blitz unusable via the key. Blitz is minimally affected as it's their default (and only?) language.

**Comment by Valanthe500** [comment]
Issue has been resolved.
German uses "g"
Blitz is "d"
and Synthetic is "b"

**Comment by EvilJackCarver** [comment]
Which PR was this fixed in, so I can link it and close?

**Comment by Valanthe500** [comment]
Fixed in #832

**Comment by EvilJackCarver** [comment]
Closed per above
