### ISSUE TITLE
Vote window is very clingy

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/NEV-Northern-Light#73]
If there's an active vote in progress, the 'close' button itself doesn't do anything. If you close it with the 'X' in the corner, it will pop back up a few seconds later. This continues until the vote properly ends, at which point you can actually close it without a return.

**Comment by ShadzFen** [comment]
I tried to fix this but it didn't go very well. I did however find an in-game workaround. 

If you hit the "Close" button on the vote window a few times, it will stop the countdown timer which will then allow you to properly close the window by pressing the X button without it popping up again. Issue seems to be something related to the window popping up every time the timer refreshes every second.

**Comment by Valanthe500** [comment]
This has FINALLY been fixed by Upstream Merge #1595
