### ISSUE TITLE
Old code makes Jumper not work on Deck 4

### ISSUE THREAD

**Issue by TwistedAkai** [Eclipse-Station/NEV-Northern-Light#897]
https://github.com/Eclipse-Station/NEV-Northern-Light/blob/c65838e1488ae730886f7bb2684a38b5eabc35d5/code/game/objects/items/weapons/teleportation.dm#L46

Z level check needs to be updated. Isn't there a proc to check that the current Z level is a station Z?

**Comment by Valanthe500** [comment]
This has been resolved in the Upstream merge #1548
